//Data Transfer Object
module.exports = class UserDto {
  email;
  id;
  roles;
  firstName;
  secondName;
  lastName;
  post;
  phone;
  companyFullName;
  companyShortName;
  companyOwnershipType;
  companyOwnershipTypeOptions;
  companyLegalAddressCode;
  companyLegalAddressCity;
  companyLegalAddressTownship;
  companyLegalAddressStreet;
  companyLegalAddressHouse;
  companyLegalAddressRoom;
  companyMailAddressCode;
  companyMailAddressCity;
  companyMailAddressTownship;
  companyMailAddressStreet;
  companyMailAddressHouse;
  companyMailAddressRoom;
  companyPhone;
  companyEmail;
  companyBank;
  companyPayment;
  companyInn;
  companyOkpo;
  companyBik;
  companyDirFirstName;
  companyDirSecondName;
  companyDirLastName;
  companyDirPost;
  companyGrounds;
  // isActivated;

  constructor(model) {
    // console.log("model:::", model);
    this.email = model.email;
    this.firstName = model.firstName;
    this.secondName = model.secondName;
    this.lastName = model.lastName;
    this.id = model._id.valueOf();
    this.roles = model.roles;
    this.post = model.post;
    this.phone = model.phone;
    this.companyFullName = model.companyFullName;
    this.companyShortName = model.companyShortName;
    this.companyOwnershipType = model.companyOwnershipType;
    this.companyOwnershipTypeOptions = model.companyOwnershipTypeOptions;
    this.companyLegalAddressCode = model.companyLegalAddressCode;
    this.companyLegalAddressCity = model.companyLegalAddressCity;
    this.companyLegalAddressTownship = model.companyLegalAddressTownship;
    this.companyLegalAddressStreet = model.companyLegalAddressStreet;
    this.companyLegalAddressHouse = model.companyLegalAddressHouse;
    this.companyLegalAddressRoom = model.companyLegalAddressRoom;
    this.companyMailAddressCode = model.companyMailAddressCode;
    this.companyMailAddressCity = model.companyMailAddressCity;
    this.companyMailAddressTownship = model.companyMailAddressTownship;
    this.companyMailAddressStreet = model.companyMailAddressStreet;
    this.companyMailAddressHouse = model.companyMailAddressHouse;
    this.companyMailAddressRoom = model.companyMailAddressRoom;
    this.companyPhone = model.companyPhone;
    this.companyEmail = model.companyEmail;
    this.companyBank = model.companyBank;
    this.companyPayment = model.companyPayment;
    this.companyInn = model.companyInn;
    this.companyOkpo = model.companyOkpo;
    this.companyBik = model.companyBik;
    this.companyDirFirstName = model.companyDirFirstName;
    this.companyDirSecondName = model.companyDirSecondName;
    this.companyDirLastName = model.companyDirLastName;
    this.companyDirPost = model.companyDirPost;
    this.companyGrounds = model.companyGrounds;
  }
};
