//Data Transfer Object
export function dtoUser(user) {
  return {
    email: user.email,
    id: user._id,
    firstName: user.firstName,
    secondName: user.secondName,
    lastName: user.lastName,
    post: user.post,
    phone: user.phone,
    companyFullName: user.companyFullName,
    companyShortName: user.companyShortName,
    companyOwnershipType: user.companyOwnershipType,
    companyOwnershipTypeOptions: user.companyOwnershipTypeOptions,
    companyLegalAddressCode: user.companyLegalAddressCode,
    companyLegalAddressCity: user.companyLegalAddressCity,
    companyLegalAddressTownship: user.companyLegalAddressTownship,
    companyLegalAddressStreet: user.companyLegalAddressStreet,
    companyLegalAddressHouse: user.companyLegalAddressHouse,
    companyLegalAddressRoom: user.companyLegalAddressRoom,
    companyMailAddressCode: user.companyMailAddressCode,
    companyMailAddressCity: user.companyMailAddressCity,
    companyMailAddressTownship: user.companyMailAddressTownship,
    companyMailAddressStreet: user.companyMailAddressStreet,
    companyMailAddressHouse: user.companyMailAddressHouse,
    companyMailAddressRoom: user.companyMailAddressRoom,
    companyPhone: user.companyPhone,
    companyEmail: user.companyEmail,
    companyBank: user.companyBank,
    companyPayment: user.companyPayment,
    companyInn: user.companyInn,
    companyOkpo: user.companyOkpo,
    companyBik: user.companyBik,
    companyDirFirstName: user.companyDirFirstName,
    companyDirSecondName: user.companyDirSecondName,
    companyDirLastName: user.companyDirLastName,
    companyDirPost: user.companyDirPost,
    companyGrounds: user.companyGrounds,
  };
}
