const { Schema, model, Types } = require("mongoose");

const schema = new Schema({
  status: { type: String, required: true },
  numberNk: { type: String, required: false },
  numberRi: { type: String, required: false },
  firstName: { type: String, required: true },
  secondName: { type: String, required: true },
  lastName: { type: String, required: true },
  gender: { type: String, required: true },
  snils: { type: String, required: false },
  post: { type: String, required: true },
  birthday: { type: Date, required: true },
  passportSeries: { type: String, required: false, default: "" },
  passportNumber: { type: String, required: false, default: "" },
  passportIssued: { type: String, required: false, default: "" },
  passportDate: { type: Date, required: false, default: "" },
  passportCode: { type: String, required: false, default: "" },
  mailCode: { type: String, required: false },
  city: { type: String, required: false },
  township: { type: String, required: false },
  street: { type: String, required: false },
  homeNumber: { type: String, required: false },
  apartment: { type: String, required: false },
  phone: { type: String, required: true },
  email: { type: String, required: true },
  education: { type: String, required: false },
  institution: { type: String, required: false },
  specialization: { type: String, required: false },
  diplomSeries: { type: String, required: false },
  diplomNumber: { type: String, required: false },
  diplomDate: { type: Date, required: false },
  attestationNk: [{ type: Object, required: false }],
  attestationRi: [{ type: Object, required: false }],
  training: [{ type: Object, required: false }],

  weldingMethodDateRde: { type: Date, required: false },
  weldingMethodDateSp: { type: Date, required: false },
  weldingMethodDateSf: { type: Date, required: false },
  weldingMethodDateMig: { type: Date, required: false },
  weldingMethodDateMag: { type: Date, required: false },
  weldingMethodDatePag: { type: Date, required: false },
  weldingMethodDatePig: { type: Date, required: false },
  weldingMethodDateVig: { type: Date, required: false },
  weldingMethodDatePs: { type: Date, required: false },
  weldingMethodDateGs: { type: Date, required: false },
  weldingMethodDateNi: { type: Date, required: false },
  weldingMethodDateZn: { type: Date, required: false },
  weldingMethodDateNg: { type: Date, required: false },
  weldingMethodDateE: { type: Date, required: false },
  methodNkDateVik: { type: Date, required: false },
  methodNkDateVd: { type: Date, required: false },
  methodNkDateTk: { type: Date, required: false },
  methodNkDatePvk: { type: Date, required: false },
  methodNkDatePvt: { type: Date, required: false },
  methodNkDateMk: { type: Date, required: false },
  methodNkDateUk: { type: Date, required: false },
  methodNkDateRk: { type: Date, required: false },
  methodNkDateMi: { type: Date, required: false },
  methodNkDate1s: { type: Date, required: false },
  typeRiDateMsi: { type: Date, required: false },
  typeRiDateMdi: { type: Date, required: false },
  typeRiDateIt: { type: Date, required: false },
  typeRiDateIks: { type: Date, required: false },
  typeRiDateTi: { type: Date, required: false },
  typeRiDateIsm: { type: Date, required: false },
  typeRiDateSe: { type: Date, required: false },
  typeRiDateSvi: { type: Date, required: false },
  weldingProductionDate: { type: Date, required: false },
  pkInfo: { type: Array, required: false },
  attNkInfo: { type: Array, required: false },
  attRiInfo: { type: Array, required: false },
  ordersTraining: [{ type: Types.ObjectId, ref: "OrderTraining" }],
  ownerUser: { type: Types.ObjectId, ref: "User" },
});

module.exports = model("Listener", schema);
